# -*- coding: utf-8 -*-


# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(248, 150)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(12, 11, 104, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(12, 37, 104, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(12, 63, 104, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(12, 89, 104, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 10, 104, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 38, 101, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoEnhancement"))
        self.pushButton.setText(_translate("MainWindow", "详情按钮坐标"))
        self.pushButton_2.setText(_translate("MainWindow", "强化按钮坐标"))
        self.pushButton_3.setText(_translate("MainWindow", "快捷放入按钮坐标"))
        self.pushButton_4.setText(_translate("MainWindow", "确认强化按钮坐标"))
        self.pushButton_5.setText(_translate("MainWindow", "关键等级强化：F7"))
        self.pushButton_6.setText(_translate("MainWindow", "满级强化：F8"))

        self.pushButton.clicked.connect(self.detail_button)
        self.pushButton_2.clicked.connect(self.enhance_button)
        self.pushButton_3.clicked.connect(self.quick_put_button)
        self.pushButton_4.clicked.connect(self.confirm_enhance_button)
        self.pushButton_5.clicked.connect(self.key_level_enhance)
        self.pushButton_6.clicked.connect(self.max_level_enhance)
        
        self.pushButton_5.setShortcut("F7")
        self.pushButton_6.setShortcut("F8")





    def detail_button(self):
        import button_details
        button_details.main()
        self.pushButton.setText("已设置")

    def enhance_button(self):
        import button_enhance
        button_enhance.main()
        self.pushButton_2.setText("已设置")

    def quick_put_button(self):
        import button_quick
        button_quick.main()
        self.pushButton_3.setText("已设置")

    def confirm_enhance_button(self):
        import button_realenhance
        button_realenhance.main()
        self.pushButton_4.setText("已设置")

    def key_level_enhance(self):
        import key_level_enhance
        key_level_enhance.main()

    def max_level_enhance(self):
        import max_level_enhance
        max_level_enhance.main()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

